### ISSUE TITLE
German translations

### ISSUE THREAD

**Issue by PWAdvanced** [frederiksen/Classic-WiX-Burn-Theme#1]
The culture and language attributes of the WixLocalization tag are not correctly set in the German localization ClassicTheme.xml file.  I believe the tag should be:
`
<WixLocalization Culture="de-de" Language="1031" xmlns="http://schemas.microsoft.com/wix/2006/localization">
`

**Comment by frederiksen** [comment]
Your are right. Will you make a [PR](https://help.github.com/en/articles/about-pull-requests)? Thank you @PWAdvanced

**Comment by PWAdvanced** [comment]
Hi @frederiksen.  I'd just like to say thanks for providing the samples, I've found them invaluable and a great help.  

Although I've been developing software commercially for many years, I am a git novice and would appreciate it if you could make the change.  


All the best



Paul

**Comment by frederiksen** [comment]
@PWAdvanced I dare you to create your first PR. It's so easy - you can do it all in the browser in one minute - here's how you do it: https://www.youtube.com/watch?v=YTbRzhQju4c

**Comment by frederiksen** [comment]
Fixed in PR: https://github.com/frederiksen/Classic-WiX-Burn-Theme/pull/3
