### ISSUE TITLE
Does not work for me.

### ISSUE THREAD

**Issue by hahoje** [frederiksen/Classic-WiX-Burn-Theme#4]
I'm trying to apply your code on my Korean project.
I ran your app but it did not work for me. I changed system language to German and ran exe but it shows English anyway. I saw some German (Yes or No)  when I click the close button to cancel the installation. I think that was from OS.
I compiled your code with wixtoolset 3.11 and visual studio 2017.
Are there any precondition that should I do?

**Comment by frederiksen** [comment]
Sample2 - https://github.com/frederiksen/Classic-WiX-Burn-Theme/tree/master/Samples/Sample2 - has translations included. Using the argument -lang you can test different translations without having a PC with that locale.

**Comment by hahoje** [comment]
Oops. I found that the LCID was miss inputted. It works! Thanks!

**Comment by frederiksen** [comment]
@hahoje great. It would be great if you could contribute with Korean translations to this project. Create a PR with Korean translations please.

**Comment by frederiksen** [comment]
Thank you @hahoje for the PR
